[workspace]
members = [".", "plot"]

[package]
name = "criterion"
description = "Statistics-driven micro-benchmarking library"
categories = ["development-tools::profiling"]
keywords = ["criterion", "benchmark"]
homepage = "https://criterion-rs.github.io/book/index.html"
authors = [
    "Jorge Aparicio <japaricious@gmail.com>",
    "Brook Heisler <brookheisler@gmail.com>",
]
# When bumping:
#
# * Update version numbers in the book;
version = "0.8.2"
edition = "2018"
# Update the MSRV variable in .github/workflows/ci.yml when changing this.
rust-version = "1.86.0"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/criterion-rs/criterion.rs"
readme = "README.md"
exclude = ["book/*"]

[dependencies]
anes = "0.2"
serde = "1.0.100"
serde_derive = "1.0.100"
serde_json = "1.0.100"
lexopt = "0.3"
walkdir = "2.3"
fastrand = "2"
regex = { version = "1.5.1", default-features = false, features = ["std"] }

# Optional dependencies
criterion-plot = { path = "plot", version = "0.8.2", optional = true }
tinytemplate = { version = "1.1", optional = true }
# Enable rayon support
rayon = { version = "1.3", optional = true }
csv = { version = "1.1", optional = true }
futures = { version = "0.3", default-features = false, features = [
    "executor",
], optional = true }
smol = { version = "2.0", default-features = false, optional = true }
tokio = { version = "1.0", default-features = false, features = [
    "rt",
], optional = true }

[target.'cfg(any(windows, unix))'.dependencies]
alloca_crate = { package = "alloca", version = "0.4", optional = true }
page_size = { version = "0.6", optional = true }

# Enable plotters support
[dependencies.plotters]
version = "^0.3.2"
optional = true
default-features = false
features = ["svg_backend", "area_series", "line_series"]

[dev-dependencies]
tempfile = "3.5.0"
approx = "0.5.0"
quickcheck = { version = "1.0", default-features = false }
rand = "0.8"
futures = "0.3"

[features]
stable = [
    "csv_output",
    "html_reports",
    "async_futures",
    "async_smol",
    "async_tokio",
]
default = ["rayon", "plotters", "alloca"]

# Enable alloca-based memory layout randomization. Reduces bias from memory
# alignment and cache effects.
alloca = ["alloca_crate", "page_size"]

# Enable async/await support
async = []

# These features enable built-in support for running async benchmarks on each different async
# runtime.
async_futures = ["futures", "async"]
async_smol = ["smol", "async"]
async_tokio = ["tokio", "async"]

# Make Criterion.rs generate its own plots (as opposed to using cargo-criterion)
html_reports = ["criterion-plot", "tinytemplate"]

# Make Criterion.rs generate CSV files. This feature is deprecated in favor of
# cargo-criterion's --message-format=json option.
csv_output = ["csv"]

[[bench]]
name = "bench_main"
harness = false

[lib]
bench = false

# Enable all of the async runtimes for the docs.rs output
[package.metadata.docs.rs]
features = ["async_futures", "async_smol", "async_tokio"]
