[package]
name = "criterion-plot"
description = "Criterion's plotting library"
categories = ["visualization"]
keywords = ["plotting", "gnuplot", "criterion"]
authors = [
    "Jorge Aparicio <japaricious@gmail.com>",
    "Brook Heisler <brookheisler@gmail.com>",
]
# When bumping:
#
# * Update version numbers in the book;
version = "0.8.2"
edition = "2018"
# Update the MSRV variable in .github/workflows/ci.yml when changing this.
rust-version = "1.86.0"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/criterion-rs/criterion.rs"
readme = "README.md"

[dependencies]

[dev-dependencies]
itertools-num = "0.1"
num-complex = { version = "0.4", default-features = false, features = ["std"] }
rand = "0.8"
